image: paritytech/ink-ci-linux:production

tasks:
  - init: cargo contract build

vscode:
  extensions:
    - matklad.rust-analyzer # Rust analyzer
    - bungcip.better-toml # TOML Support 
    - serayuzgur.crates # Crates Support
    - belfz.search-crates-io # Search from Creates from within VSCode
    - https://github.com/paritytech/vscode-substrate/releases/download/v0.5.2/vscode-substrate.vsix # Substrate VSCode extension

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod